#!/usr/bin/env python3
"""Turn a folder of "<n>s Large.jpeg" / "<n>p Large.jpeg" files into the garden.

  python3 tools/build_garden.py "S for Sketches；P for Photos"

For every day n it writes assets/dayNN-sketch.webp (ink on transparent) and
assets/dayNN-photo.webp, then regenerates data.js. Titles / captions are read
from captions.json (optional): {"3": {"title": "...", "caption": "..."}}.
"""
import hashlib, json, os, re, sys
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOTAL = 100
PAT = re.compile(r"^(\d+)\s*([sp])\b.*\.(jpe?g|png|webp)$", re.I)


def sketch_to_ink(im):
    """White paper -> transparent, black ink -> opaque (works for jpeg noise too)."""
    L = ImageOps.exif_transpose(im).convert("L")
    if max(L.size) > 900:
        L.thumbnail((900, 900), Image.LANCZOS)
    a = L.point(lambda v: 0 if v >= 235 else 255 if v <= 40 else int((235 - v) * 255 / 195))
    out = Image.merge("RGBA", [Image.new("L", L.size, 24)] * 3 + [a])
    return out


def photo_small(im):
    im = ImageOps.exif_transpose(im).convert("RGB")
    im.thumbnail((1200, 1200), Image.LANCZOS)
    return im


def tag(path):
    return hashlib.md5(open(path, "rb").read()).hexdigest()[:8]


def main(folder):
    found = {}
    for f in os.listdir(folder):
        m = PAT.match(f)
        if m:
            found.setdefault(int(m.group(1)), {})[m.group(2).lower()] = os.path.join(folder, f)
    days = sorted(d for d, v in found.items() if "s" in v and "p" in v)
    skipped = sorted(set(found) - set(days))
    caps = {}
    cp = os.path.join(ROOT, "captions.json")
    if os.path.exists(cp):
        caps = json.load(open(cp, encoding="utf8"))

    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    entries = []
    for d in days:
        s_out = f"assets/day{d:02d}-sketch.webp"
        p_out = f"assets/day{d:02d}-photo.webp"
        sketch_to_ink(Image.open(found[d]["s"])).save(os.path.join(ROOT, s_out), quality=88, method=6, alpha_quality=100)
        photo_small(Image.open(found[d]["p"])).save(os.path.join(ROOT, p_out), quality=82, method=6)
        c = caps.get(str(d), {})
        entries.append({
            "day": d,
            "title": c.get("title", ""),
            "sketch": f"{s_out}?v={tag(os.path.join(ROOT, s_out))}",
            "photo": f"{p_out}?v={tag(os.path.join(ROOT, p_out))}",
            "caption": c.get("caption", ""),
        })

    body = ",\n".join("    " + json.dumps(e, ensure_ascii=False) for e in entries)
    open(os.path.join(ROOT, "data.js"), "w", encoding="utf8").write(
        "// Generated by tools/build_garden.py. Titles and captions live in captions.json.\n"
        "window.GARDEN = {\n"
        "  title: \"Keyi's Garden\",\n"
        f"  total: {TOTAL},\n"
        "  entries: [\n" + body + ",\n  ],\n};\n"
    )
    print(f"built {len(days)} days: {days[0]}..{days[-1]}")
    if skipped:
        print("skipped (need both sketch and photo):", skipped)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "S for Sketches；P for Photos")
